name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.25.1'  # match your version

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./... -v
